// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbiuubkbqptxrcnuorjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiaXV1YmticXB0eHJjbnVvcmpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTU0NzYsImV4cCI6MjA2NTUzMTQ3Nn0.gxebwIM2EDVHFQ1q8K0dN291XeHIp9QTQ4SXUUIHpuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);